const C=window.ZEN_CONFIG||{};let token=localStorage.getItem('zen_admin_token'),page=(location.hash||'#Dashboard').slice(1)||'Dashboard',D={};const $=id=>document.getElementById(id);const navs=['Dashboard','Users','Devices','Activity','Mining','Wallets','Withdrawals','Transactions','Earnings','Reports','Notifications','Settings'];
const api=(path,opt={})=>fetch(C.supabaseUrl+path,{...opt,headers:{apikey:C.supabaseAnonKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}}).then(async r=>{let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||j.msg||'Request failed');return j});
const edge=(name,body)=>api('/functions/v1/'+name,{method:'POST',body:JSON.stringify(body||{})});const money=v=>'৳'+Number(v||0).toFixed(2);
function go(next,replace=false){page=next;const u='#'+encodeURIComponent(next);if(replace)history.replaceState({page:next},'',u);else history.pushState({page:next},'',u);render()}
window.addEventListener('popstate',()=>{page=(location.hash||'#Dashboard').slice(1)||'Dashboard';render()});
window.addEventListener('hashchange',()=>{page=decodeURIComponent((location.hash||'#Dashboard').slice(1))||'Dashboard';render()});
function tbl(h,rows){return `<table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function load(){if(!C.supabaseUrl){$('sync').textContent='Configure config.js';return}try{D=await edge('admin-dashboard');$('sync').textContent='Live'}catch(e){$('sync').textContent=e.message}}
async function render(){ $('title').textContent=page;$('nav').innerHTML=navs.map(x=>`<button class="${x===page?'active':''}" onclick="go('${x}')">${x}</button>`).join('');await load();let ds=D.devices||[],ws=D.withdrawals||[],wallets=D.wallets||[];let html='';
if(page==='Dashboard')html=`<div class="stats"><div class="stat"><span>Total Devices</span><strong>${ds.length}</strong></div><div class="stat"><span>Online</span><strong>${ds.filter(x=>x.status==='online').length}</strong></div><div class="stat"><span>Total Balance</span><strong>${money(wallets.reduce((a,x)=>a+Number(x.available_balance||0),0))}</strong></div><div class="stat"><span>Pending Withdrawals</span><strong>${ws.filter(x=>x.status==='pending').length}</strong></div></div><div class="grid"><div class="panel"><h3>Device Activity</h3><p>Registered devices</p>${tbl(['User','Device','Model','Status','Last Seen'],ds.slice(0,12).map(x=>[x.user_id,x.device_name||'-',x.model||'-',`<span class="pill ${x.status==='online'?'on':''}">${x.status}</span>`,x.last_seen_at||'-']))}</div><div class="panel"><h3>Withdrawal Requests</h3><p>Admin controlled</p>${tbl(['User','Amount','Status','Action'],ws.filter(x=>x.status==='pending').slice(0,8).map(x=>[x.user_id,money(x.amount),`<span class="pill pending">${x.status}</span>`,`<span class="actions"><button onclick="approve('${x.id}')">Approve</button><button onclick="rejectW('${x.id}')">Reject</button></span>`]))}</div></div>`;
else if(page==='Devices')html=`<div class="panel"><h3>Devices</h3>${tbl(['User','Device','Model','Android','Status','Mining','Last Seen'],ds.map(x=>[x.user_id,x.device_name||'-',x.model||'-',x.android_version||'-',x.status,x.mining_status,x.last_seen_at||'-']))}</div>`;
else if(page==='Withdrawals')html=`<div class="panel"><h3>Withdrawals</h3>${tbl(['User','Amount','Method','Status','Requested','Action'],ws.map(x=>[x.user_id,money(x.amount),x.payment_method,x.status,x.requested_at||'-',x.status==='pending'?`<span class="actions"><button onclick="approve('${x.id}')">Approve</button><button onclick="rejectW('${x.id}')">Reject</button></span>`:'-']))}</div>`;
else if(page==='Users')html=`<div class="panel"><h3>Users</h3>${tbl(['User','Balance','Earned','Devices'],wallets.map(x=>[x.user_id,money(x.available_balance),money(x.total_earned),ds.filter(d=>d.user_id===x.user_id).length]))}</div>`;
else if(page==='Wallets')html=`<div class="panel"><h3>Wallets</h3>${tbl(['User','Available','Earned','Withdrawn','Pending'],wallets.map(x=>[x.user_id,money(x.available_balance),money(x.total_earned),money(x.total_withdrawn),money(x.pending_amount)]))}</div>`;
else if(page==='Activity')html=`<div class="panel"><h3>Device Activity</h3><p>App/package usage metadata only · Open sessions are marked Active.</p>${tbl(['Device','Package','App','Started','Ended','Duration','Status'],(D.activities||[]).map(x=>[x.device_id,x.package_name,x.app_name,x.started_at,x.ended_at||'-',x.duration_seconds?Math.round(Number(x.duration_seconds)/60)+' min':'-',x.ended_at?'Completed':'Active']))}</div>`;
else if(page==='Mining')html=`<div class="panel"><h3>Mining Management</h3><p>Global rate: ${money(D.config?.global_rate)} / 24h · Mining ${D.config?.global_enabled?'enabled':'disabled'} · Withdrawal ${D.config?.withdrawal_enabled?'unlocked':'locked'}</p>${tbl(['Device','Status','Rate'],ds.map(x=>[x.device_name||x.id,x.mining_status,money(x.mining_rate)]))}</div>`;
else if(page==='Earnings')html=`<div class="panel"><h3>Earnings</h3><p>Server-authoritative wallet totals</p>${tbl(['User','Total Earned'],wallets.map(x=>[x.user_id,money(x.total_earned)]))}</div>`;
else if(page==='Notifications')html=`<div class="panel"><h3>Notifications</h3><div class="empty">Notifications are generated by backend events and can be surfaced here.</div></div>`;
else if(page==='Transactions')html=`<div class="panel"><h3>Transactions</h3><p>Reward and wallet ledger entries are server-authoritative.</p>${tbl(['User','Type','Amount','Created'],(D.transactions||[]).map(x=>[x.user_id,x.type||'-',money(x.amount),x.created_at||'-']))}</div>`;
else if(page==='Reports')html=`<div class="panel"><h3>Reports</h3><p>Current production snapshot.</p><div class="stats"><div class="stat"><span>Activity Sessions</span><strong>${(D.activities||[]).length}</strong></div><div class="stat"><span>Wallets</span><strong>${wallets.length}</strong></div><div class="stat"><span>Withdrawals</span><strong>${ws.length}</strong></div></div></div>`;
else if(page==='Settings')html=`<div class="panel"><h3>Settings</h3><p>Global controls are read from the server. Mutating controls should be wired through authenticated admin actions before release.</p>${tbl(['Setting','Value'],[['Global mining',D.config?.global_enabled?'Enabled':'Disabled'],['Global rate',money(D.config?.global_rate)+' / 24h'],['Withdrawal',D.config?.withdrawal_enabled?'Unlocked':'Locked']])}</div>`;
else html=`<div class="panel"><h3>${page}</h3><p>Production control surface connected to the server-authoritative backend.</p></div>`;$('view').innerHTML=html}
window.approve=async id=>{try{await edge('admin-action',{action:'approve_withdrawal',withdrawalId:id});render()}catch(e){alert(e.message)}};window.rejectW=async id=>{const reason=prompt('Reason','Rejected by admin')||'Rejected';try{await edge('admin-action',{action:'reject_withdrawal',withdrawalId:id,reason});render()}catch(e){alert(e.message)}};
$('loginBtn').onclick=async()=>{try{if(!C.supabaseUrl||!C.supabaseAnonKey)throw Error('Configure admin_web/config.js first');const r=await fetch(C.supabaseUrl+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:C.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});const j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||'Login failed');token=j.access_token;localStorage.setItem('zen_admin_token',token);location.reload()}catch(e){$('msg').textContent=e.message}};if(token){$('login').classList.add('hidden');$('app').classList.remove('hidden');render()}else{$('login').classList.remove('hidden');$('app').classList.add('hidden')}$('logout').onclick=()=>{localStorage.removeItem('zen_admin_token');location.reload()};
