import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../widgets/zen_logo.dart';
import '../widgets/green_button.dart';
import 'permissions.dart';
class RegisterScreen extends StatefulWidget{const RegisterScreen({super.key});@override State<RegisterScreen>createState()=>_RegisterState();}
class _RegisterState extends State<RegisterScreen>{final name=TextEditingController(),email=TextEditingController(),password=TextEditingController();bool busy=false;String? error;
Future<void> register()async{setState(()=>busy=true);try{final r=await Supabase.instance.client.auth.signUp(email:email.text.trim(),password:password.text,data:{'name':name.text.trim()});if(r.session!=null&&mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const PermissionsScreen()));else if(mounted)setState(()=>error='Check your email to confirm the account, then log in.');}on AuthException catch(e){setState(()=>error=e.message);}catch(e){setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
@override void dispose(){name.dispose();email.dispose();password.dispose();super.dispose();}
@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Center(child:ZenLogo(size:58)),const SizedBox(height:14),const Center(child:Text('ZEN MINING',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900))),const SizedBox(height:28),const Text('Create Account',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const Text('Join and start earning today',style:TextStyle(color:Color(0xFF91A9A0))),const SizedBox(height:22),const Text('Full Name'),const SizedBox(height:7),TextField(controller:name,decoration:const InputDecoration(hintText:'Enter your name')),const SizedBox(height:14),const Text('Email'),const SizedBox(height:7),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(hintText:'Enter your email')),const SizedBox(height:14),const Text('Password'),const SizedBox(height:7),TextField(controller:password,obscureText:true,decoration:const InputDecoration(hintText:'Create a password')),if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:Color(0xFFFF5470)))),const SizedBox(height:20),GreenButton(label:busy?'Creating...':'Register',onTap:busy?null:register)]))));}
